---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/Digital.ai Deploy
  home: Digital.ai - Official/Workflows/Digital.ai Deploy
spec:
  - template: Deploy setup deployment provider
    description: Create required connections for Deploy deployment provider
    scheduledStartDate: 2024-08-28T09:00:00+02:00
    dueDate: 2024-08-28T10:00:00+02:00
    phases:
      - phase: User Input
        tasks:
          - name: Check if remote runner exists
            type: xlrelease.ScriptTask
            script: |-
              def check_runners(runners):
                for runner in runners:
                  if runner["enabled"] and"remote" in runner["capabilities"]:
                    return True
                return False
              
              runners = configurationApi.searchByTypeAndTitle("xlrelease.JobRunner", "")
              
              if not check_runners(runners):
                raise Exception("There is no job runner with 'remote' capability enabled")
          - name: Choose connection
            type: xlrelease.UserInputTask
            description: Choose Deploy server which you want to be configured.
            variables:
              - server
        color: "#3d6c9e"
      - phase: Configure connection
        tasks:
          - name: Setup deployment provider
            type: xlrelease.ScriptTask
            description: Creates required configuration items in Release for connection
              to deployment provider.
            script: |-
              from com.xebialabs.xlrelease.api.v1.forms import DeploymentProviderSetup
              
              folderId = getCurrentFolder().getId()
              serverId = releaseVariables['server']
              
              deploymentProviderSetup = DeploymentProviderSetup(folderId, serverId)
              
              statusWebhookEventSourceId = deploymentProviderApi.setupDeploymentProvider(deploymentProviderSetup)
              
              releaseVariables['statusWebhookEventSourceId'] = statusWebhookEventSourceId
          - name: Autoconfigure deployment provider
            type: xlrelease.ScriptTask
            description: Generates Deploy CIs required to enable live event notifications.
            script: |-
              autoConfigResponse = deploymentProviderApi.autoconfigureDeploymentProvider("${statusWebhookEventSourceId}")
              
              releaseVariables['autoconfigMessage'] = autoConfigResponse.message
              releaseVariables['autoconfigUrl'] = autoConfigResponse.url
              releaseVariables['autoconfigDetails'] = autoConfigResponse.details
        color: "#3d6c9e"
      - phase: Final
        tasks:
          - name: Autoconfig response
            type: xlrelease.Task
            description: |-
              ${autoconfigMessage}
              
              [View in Deploy](${autoconfigUrl})
        color: "#3d6c9e"
    kind: WORKFLOW
    categories:
      - Application onboarding
      - Create Deployment Provider
    tags:
      - Remote Deploy
      - deployment provider
      - new
    variables:
      - type: xlrelease.StringVariable
        key: statusWebhookEventSourceId
        requiresValue: false
        showOnReleaseStart: false
      - type: xlrelease.ReferenceVariable
        key: server
        requiresValue: false
        showOnReleaseStart: false
        label: Deploy server
        referencedType: digitalai.DeployServer
      - type: xlrelease.StringVariable
        key: autoconfigMessage
        requiresValue: false
        showOnReleaseStart: false
        label: Response message
      - type: xlrelease.StringVariable
        key: autoconfigUrl
        requiresValue: false
        showOnReleaseStart: false
        label: Response URL
      - type: xlrelease.StringVariable
        key: autoconfigDetails
        requiresValue: false
        showOnReleaseStart: false
        label: Response details
    disableNotifications: true
    author: Digital.ai
    logo:
      type: xlrelease.TemplateLogo
      contentType: image/svg+xml
      file: !file "template-logo/97662a62108c2b1e1875c8e18f6d1c72a013d33c/deploy.svg"
    defaultTargetFolder: Digital.ai - Official/Workflow Executions
