---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/ArgoCD
  home: Digital.ai - Official/Workflows/ArgoCD
spec:
  - template: ArgoCD delete live deployment configuration
    description: Delete ArgoCD live deployment configuration
    scheduledStartDate: 2024-09-10T12:33:53.874+02:00
    dueDate: 2024-09-10T13:33:53.874+02:00
    phases:
      - phase: Delete live deployment config
        tasks:
          - name: Delete live deployment configuration
            type: xlrelease.ScriptTask
            description: Deletes deployment configuration from event source and from system.
            script: |-
              from com.xebialabs.xlrelease.domain import Configuration
              from com.xebialabs.deployit.plugin.api.reflect import Type
              
              statusWebhookEventSource = configurationApi.getConfiguration("${statusWebhookEventSourceId}")
              liveDeploymentConfigs = statusWebhookEventSource.getProperty("liveDeploymentConfigs")
              
              configToDelete = None
              for config in statusWebhookEventSource.getProperty("liveDeploymentConfigs"):
                if config.id == "${liveDeploymentConfigurationId}":
                  configToDelete = config
                  break
              
              if configToDelete:
                liveDeploymentConfigs.remove(configToDelete)
                statusWebhookEventSource.setProperty("liveDeploymentConfigs", liveDeploymentConfigs)
                configurationApi.updateConfiguration("${statusWebhookEventSourceId}", statusWebhookEventSource)
                configurationApi.deleteConfiguration(configToDelete.id)
          - name: Patch ArgoCD applications
            type: xlrelease.ScriptTask
            description: |-
              Patches ArgoCD applications by running a container script, adding the necessary annotation to enable live event notifications.
              
              The following annotation is applied to all apps matching the specified filter:
              `notifications.argoproj.io/subscribe.on-app-status-changed.release-webhook`
            script: |-
              from java.lang import Throwable

              try:
                deploymentServerApi.patchDeploymentServer("${statusWebhookEventSourceId}")
              except Throwable as e:
                if "Cannot find active remote runner" in str(e):
                  raise Exception("Failed to find active remote runner for executing container script.")
                raise
        color: "#3d6c9e"
    kind: WORKFLOW
    categories:
      - Application onboarding
    tags:
      - Remote ArgoCD
      - deployment server
      - delete
    variables:
      - type: xlrelease.StringVariable
        key: statusWebhookEventSourceId
      - type: xlrelease.StringVariable
        key: liveDeploymentConfigurationId
        requiresValue: false
    disableNotifications: true
    author: Digital.ai
    logo:
      type: xlrelease.TemplateLogo
      contentType: image/png
      file: !file "template-logo/c9e27d5b1d5ed9738d58781439732acacd6b482d/argocd.svg"
    defaultTargetFolder: Digital.ai - Official/Workflow Executions
